/* Generated By:JavaCC: Do not edit this line. FormulaFinderConstants.java */
package am.profclub.ws.calculation.parser;

public interface FormulaFinderConstants {

  int EOF = 0;
  int TEXT = 1;
  int FORMULA_START = 2;
  int OPEN_BRACE = 3;
  int CLOSE_BRACE = 4;
  int QUOTE = 5;
  int SINGLE_QUOTE = 6;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "<TEXT>",
    "\"{!\"",
    "\"{\"",
    "\"}\"",
    "\"\\\"\"",
    "\"\\\'\"",
  };

}
